/*
 * generated by Xtext 2.9.2
 */
package org.example.domainmodel.idea.lang


class DomainmodelFileType extends AbstractDomainmodelFileType {
	public static final DomainmodelFileType INSTANCE = new DomainmodelFileType()
	
	new() {
		super(DomainmodelLanguage.INSTANCE)
	}
}
