/*
 * generated by Xtext 2.9.2
 */
package org.example.domainmodel.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class DomainmodelIdeaModule extends AbstractDomainmodelIdeaModule {
}
